import { t } from '../i18n';

let labels: Record<string, string> | null = null;

/** Human-readable label for a plant tag slug, in the active language. Unknown tags show the slug with spaces. */
export function tagLabel(tag: string): string {
  labels ??= {
    'acid-soil': t('acid soil'),
    'acid-tolerant': t('acid tolerant'),
    'annual-flower': t('annual flower'),
    'asian-greens': t('asian greens'),
    'autumn-colour': t('autumn colour'),
    'autumn-flowering': t('autumn flowering'),
    'autumn-fruit': t('autumn fruit'),
    'autumn-planted': t('autumn planted'),
    bedding: t('bedding'),
    'beneficial-insects': t('beneficial insects'),
    berry: t('berry'),
    biennial: t('biennial'),
    biofumigant: t('biofumigant'),
    brassica: t('brassica'),
    bulb: t('bulb'),
    bush: t('bush'),
    'cane-fruit': t('cane fruit'),
    climber: t('climber'),
    'cold-season': t('cold season'),
    companion: t('companion'),
    container: t('container'),
    corm: t('corm'),
    cottage: t('cottage'),
    culinary: t('culinary'),
    'cut-and-come-again': t('cut and come again'),
    'cut-flower': t('cut flower'),
    'deciduous-conifer': t('deciduous conifer'),
    'deep-rooted': t('deep rooted'),
    dioecious: t('dioecious'),
    'dried-flower': t('dried flower'),
    'drought-tolerant': t('drought tolerant'),
    'dry-seed': t('dry seed'),
    early: t('early'),
    'early-flowering': t('early flowering'),
    edging: t('edging'),
    'edible-flowers': t('edible flowers'),
    'evening-scent': t('evening scent'),
    evergreen: t('evergreen'),
    fast: t('fast'),
    fern: t('fern'),
    'fertiliser-plant': t('fertiliser plant'),
    flower: t('flower'),
    foliage: t('foliage'),
    'forced-shoots': t('forced shoots'),
    forcing: t('forcing'),
    fragrant: t('fragrant'),
    fruit: t('fruit'),
    'fruit-tree': t('fruit tree'),
    fruiting: t('fruiting'),
    grain: t('grain'),
    grass: t('grass'),
    'green-manure': t('green manure'),
    'greenhouse-in-cool-climates': t('greenhouse in cool climates'),
    groundcover: t('groundcover'),
    'hanging-basket': t('hanging basket'),
    'heat-loving': t('heat loving'),
    'heat-tolerant': t('heat tolerant'),
    hedging: t('hedging'),
    herb: t('herb'),
    'invasive-warning': t('invasive warning'),
    'late-flowering': t('late flowering'),
    leaf: t('leaf'),
    leafy: t('leafy green'),
    legume: t('legume'),
    'long-flowering': t('long flowering'),
    'long-lived': t('long lived'),
    'long-season': t('long season'),
    'low-maintenance': t('low maintenance'),
    medicinal: t('medicinal'),
    microgreens: t('microgreens'),
    'moist-soil': t('moist soil'),
    'my-plant': t('my plant'),
    'native-fi': t('native fi'),
    naturalises: t('naturalises'),
    naturalising: t('naturalising'),
    'needs-pollinator': t('needs pollinator'),
    'nitrogen-fixer': t('nitrogen fixer'),
    nordic: t('nordic'),
    'nurse-crop': t('nurse crop'),
    nut: t('nut'),
    ornamental: t('ornamental'),
    'ornamental-edible': t('ornamental edible'),
    'overwinter-indoors': t('overwinter indoors'),
    perennial: t('perennial plant'),
    'perennial-flower': t('perennial flower'),
    'perennial-vegetable': t('perennial vegetable'),
    pods: t('pods'),
    pollinators: t('pollinators'),
    pollinizer: t('pollinizer'),
    quick: t('quick'),
    'rock-garden': t('rock garden'),
    root: t('root'),
    'root-tuber': t('root tuber'),
    'rose-hips': t('rose hips'),
    salad: t('salad'),
    'seed-heads': t('seed heads'),
    'seed-spice': t('seed spice'),
    'self-fertile': t('self fertile'),
    'self-seeds': t('self seeds'),
    shade: t('shade'),
    'shade-tolerant': t('shade tolerant'),
    'shade-tree': t('shade tree'),
    'short-day-sensitive': t('short day sensitive'),
    shrub: t('shrub'),
    'small-space': t('small space'),
    'small-tree': t('small tree'),
    'soil-structure': t('soil structure'),
    sprawling: t('sprawling'),
    spreading: t('spreading'),
    spring: t('spring'),
    'spring-flowering': t('spring flowering'),
    staple: t('staple'),
    stem: t('stem'),
    'stone-fruit': t('stone fruit'),
    storage: t('storage'),
    'street-tree': t('street tree'),
    succulent: t('succulent'),
    suckering: t('suckering'),
    tall: t('tall'),
    tea: t('tea'),
    'tender-perennial': t('tender perennial'),
    thornless: t('thornless'),
    thorny: t('thorny'),
    topiary: t('topiary'),
    toxic: t('toxic'),
    'toxic-to-cats': t('toxic to cats'),
    'trap-crop': t('trap crop'),
    tree: t('tree'),
    tuber: t('tuber'),
    'very-hardy': t('very hardy'),
    'weed-suppressing': t('weed suppressing'),
    wildflower: t('wildflower'),
    wildlife: t('wildlife'),
    'wild-harvest': t('wild harvest'),
    'wind-pollinated': t('wind pollinated'),
    'winter-cover': t('winter cover'),
    'winter-hardy': t('winter hardy'),
    'winter-structure': t('winter structure'),
  };
  return labels[tag] ?? tag.replace(/-/g, ' ');
}

/** Tags with a label (used by the dataset test). */
export function hasTagLabel(tag: string): boolean {
  tagLabel(tag);
  return tag in labels!;
}
